name: Build and test project modules

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setting up .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '7.0.x'

      - name: Build docker images
        run: docker-compose down && docker-compose build --no-cache patientms

      - name: Start docker containers
        run: docker-compose up -d patient rabbitmq postgres
      
      - name: Test patient module
        run: dotnet test --verbosity normal
        env: 
          POSTGRES_CONNECTIONSTRING: User ID=postgres;Password=changeme;Host=postgres;Port=15432;Database=patienttests

      - name: Stop docker
        if: success() || failure()
        run: docker-compose down
